export interface Database {
  public: {
    Tables: {
      leads: {
        Row: {
          id: string;
          email: string | null;
          phone: string | null;
          phone_formatted: string | null;
          description: string | null;
          client: string | null;
          status: 'Potential' | 'Active' | 'Inactive';
          location: string;
          source: string | null;
          timezone: string;
          script: string | null;
          phone_status: string | null;
          phone_type: string | null;
          api_url: string | null;
          date_created: string | null;
          date_updated: string | null;
          created_by: string | null;
          updated_by: string | null;
          custom_fields: Record<string, any> | null;
          first_name: string;
          last_name: string | null;
          transfer_ext: string | null;
          lead_type: string | null;
          crm_id: string | null;
        };
        Insert: {
          id?: string;
          email?: string | null;
          phone?: string | null;
          phone_formatted?: string | null;
          description?: string | null;
          client?: string | null;
          status?: 'Potential' | 'Active' | 'Inactive';
          location: string;
          source?: string | null;
          timezone?: string;
          script?: string | null;
          phone_status?: string | null;
          phone_type?: string | null;
          api_url?: string | null;
          date_created?: string | null;
          date_updated?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          custom_fields?: Record<string, any> | null;
          first_name: string;
          last_name?: string | null;
          transfer_ext?: string | null;
          lead_type?: string | null;
          crm_id?: string | null;
        };
        Update: {
          id?: string;
          email?: string | null;
          phone?: string | null;
          phone_formatted?: string | null;
          description?: string | null;
          client?: string | null;
          status?: 'Potential' | 'Active' | 'Inactive';
          location?: string;
          source?: string | null;
          timezone?: string;
          script?: string | null;
          phone_status?: string | null;
          phone_type?: string | null;
          api_url?: string | null;
          date_created?: string | null;
          date_updated?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          custom_fields?: Record<string, any> | null;
          first_name?: string;
          last_name?: string | null;
          transfer_ext?: string | null;
          lead_type?: string | null;
          crm_id?: string | null;
        };
      };
      profiles: {
        Row: {
          id: string;
          first_name: string;
          last_name: string;
          email: string;
          role: string;
          is_active: boolean;
          date_created: string;
          date_updated: string | null;
          created_by: string | null;
          updated_by: string | null;
          avatar_url: string | null;
          phone: string | null;
          timezone: string | null;
          settings: Record<string, any> | null;
        };
        Insert: {
          id?: string;
          first_name: string;
          last_name: string;
          email: string;
          role?: string;
          is_active?: boolean;
          date_created?: string;
          date_updated?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          avatar_url?: string | null;
          phone?: string | null;
          timezone?: string | null;
          settings?: Record<string, any> | null;
        };
        Update: {
          id?: string;
          first_name?: string;
          last_name?: string;
          email?: string;
          role?: string;
          is_active?: boolean;
          date_created?: string;
          date_updated?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          avatar_url?: string | null;
          phone?: string | null;
          timezone?: string | null;
          settings?: Record<string, any> | null;
        };
      };
    };
  };
}