// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czrcrxgxvbmxycszvuag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6cmNyeGd4dmJteHljc3p2dWFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5NTAxNjcsImV4cCI6MjA1MTUyNjE2N30.eOySQ3GEithMwHAZy0s_m7SWMaqQzC9WvQ1KXQrku9k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);